# Open AI configuration
openai_api_key: ""

# Label Studio configuration
label_studio_url: "http://localhost:8080"
label_studio_api_key: ""
project_id: 4
data_storage: "local" # We support "local" and "remote"
data_dir: "E:\\Code\\KAIST\\DEAL-ShoeDesign\\ChatGPT_ShoeGen\\dataset\\project_4"
template: ".\\result_templates\\project_4_result_template.json"